[project]
name = "ubpe"
version = "0.2.2"
description = "UBPE Tokenizer"
authors = [{ name = "Scurrra (Ilja Baroŭski)", email = "iscurrra@gmail.com" }]
license-files = ["LICENSE"]
readme = "README.md"
classifiers = [
    "Programming Language :: Python :: 3",
    "Development Status :: 4 - Beta",
]
requires-python = ">=3.12"
dependencies = []

[project.optional-dependencies]
native = ["ubpe-native>=0.2.2"]
cython = ["ubpe-cython>=0.2.2"]

[project.urls]
Repository = "https://github.com/Scurrra/ubpe.git"
Issues = "https://github.com/Scurrra/ubpe/issues"

[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.poetry]
exclude = ["ubpe-native/", "ubpe-cython/"]
